" Basic Stuff {
call pathogen#infect()
    syntax on
    filetype plugin indent on
    set nocompatible "vim, not vi
    set t_Co=256
    set omnifunc=syntaxcomplete#Complete "Turn on OmniCompletion

    scriptencoding utf-8
    set encoding=utf-8

    set viminfo='100,<1000,s10,h

    syntax enable

    set background=dark
    " solarized options 
    let g:solarized_termtrans = 1
    let g:solarized_termcolors = 256
    colorscheme solarized
" }

"" Options {
    set nohidden "remove the buffer when the tab is closed
    set wildmode=longest:full
    set wildmenu " better command-line completion
    set showcmd " partial commands in the last line
    set hlsearch " may want to change this to underline
    set showmatch  " show matching bracket
" }

" Usability {
    set ruler "show where we are
    set laststatus=2 "display the status line always
    set cmdheight=2 "two lines at the bottom, to keep things from getting hidden
    set pastetoggle=<F5> "so we can paste stuff without annoying indents
    set number

    " Show Whitespace
    set list
    set listchars=eol:¶,tab:»·,trail:ˍ,extends:›,precedes:‹ " Some other good chars (˷˽)
    hi SpecialText ctermfg=235 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=235 ctermbg=NONE cterm=NONE

    " This toggles a paste mode that will turn off line numbers, the mouse, and list if they are enabled
    let g:old_nu=&nu " Sets the NU remember mode
    let g:old_mouse=&mouse " Sets the mouse remember mode
    let g:old_list=&list " Sets the mouse remember mode
    imap <silent> <F2> <Esc><F2>a
    nmap <silent> <F2> :if &paste <Bar>
                \set nopaste <Bar>
                \let &nu=g:old_nu <Bar>
                \let &mouse=g:old_mouse <Bar>
                \let &list=g:old_list <Bar>
                \echo "(nu="g:old_nu") (mouse="g:old_mouse") (list="g:old_list") (paste= 0 )"<bar>
                \else <Bar>
                \let g:old_nu=&nu <Bar>
                \let g:old_mouse=&mouse <Bar>
                \let g:old_list=&list <Bar>
                \let &nu=0 <Bar>
                \let &mouse="" <Bar>
                \let &list=0 <Bar>
                \let &paste=1 <Bar>
                \echo "(nu= 0 ) (mouse=  ) (list= 0 ) (paste= 1 )"<bar>
                \endif <cr>

    " Toggle numbered lines on F3
    imap <silent> <F3> <Esc><F3>a
    nmap <F3> :set number! number?<Bar>
                \echo "(nu="&nu") (mouse="&mouse") (list="&list") (paste="&paste")"<cr>

    " Toggle mouse on F4
    imap <silent> <F4> <Esc><F4>a
    nmap <F4> :if &mouse=="" <Bar>
                \let &mouse="a" <Bar>
                \echo "(nu="&nu") (mouse= a ) (list="&list") (paste="&paste")"<bar>
                \else <Bar>
                \let &mouse="" <Bar>
                \echo "(nu="&nu") (mouse=  ) (list="&list") (paste="&paste")"<bar>
                \endif<cr>
" }


" indentation {
    set autoindent "indentation
    set shiftwidth=2
    set softtabstop=2
    set expandtab
    set backspace=indent,eol,start
    " set textwidth=79
    set tabstop=8
" }
 
" nerdtree {
    let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
    noremap gn :NERDTree<Cr>

    " Switch Between Buffers
    map  <C-l> :bn<CR>
    map  <C-h> :bp<CR>
    map  <C-t> :NERDTreeToggle<cr>

    "  How can I close vim if the only window left open is a NERDTree?
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" }

" tmuxline {
  let g:tmuxline_separators = {
        \ 'left' : '',
        \ 'left_alt': '>',
        \ 'right' : '',
        \ 'right_alt' : '<',
        \ 'space' : ' '}
" }

" Unsorted {
    set shortmess+=filmnrxoOtT      " abbrev. of messages (avoids 'hit enter')
    set viewoptions=folds,options,cursor,unix,slash " better unix / windows compatibility
    set virtualedit=onemore         " allow for cursor beyond last character
    set history=1000                " Store a ton of history (default is 20)
    set spell                       " spell checking on
    hi clear SpellBad
    hi SpellBad cterm=underline
    set showmode "display the current mode
    set cursorline "highlights the light we're on
    "set cursorcolumn "highlights the light we're on
    hi clear cursorline "We don't want an underline
    "hi clear cursorcolumn "We don't want an underline
    hi cursorline guibg=#111111 ctermbg=233 "Sets the highlight color
    "hi CursorColumn guibg=#333333 ctermbg=0 "highlights the cursor
    set whichwrap=b,s,h,l,<,>,[,] "wrap backspace and cursor

    "folding settings
    set foldmethod=indent   "fold based on indent
    set foldnestmax=10      "deepest fold is 10 levels
    set nofoldenable        "dont fold by default
    set foldlevel=1         "this is just what i use
    let g:vim_markdown_initial_foldlevel=100 "Markdown plugin defaults to being folded

    "jsbeautify
    autocmd FileType javascript vnoremap <buffer>  <c-f> :call RangeJsBeautify()<cr>
    autocmd FileType javascript nnoremap <buffer>  <c-f> :call JsBeautify()<cr>
    autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
    autocmd FileType html nnoremap <buffer> <c-f> :call HtmlBeautify()<cr>
    autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>
    autocmd FileType css nnoremap <buffer> <c-f> :call CSSBeautify()<cr>
    autocmd FileType mss vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>
    autocmd FileType mss nnoremap <buffer> <c-f> :call CSSBeautify()<cr>

    "Filetypes
    au BufRead,BufNewFile *.mss set filetype=carto
    au BufRead,BufNewFile *.{json,geojson} set filetype=javascript

    " Signify
    let g:signify_vcs_list = [ 'git' ]
" }
