" Basic Stuff {
    call pathogen#infect()
    syntax on
    filetype plugin indent on
    set nocompatible "vim, not vi
    set ofu=syntaxcomplete#Complete "Turn on OmniCompletion
" }

" Options {
    set nohidden "remove the buffer when the tab is closed
    set wildmode=longest:full
    set wildmenu " better command-line completion
    set showcmd " partial commands in the last line
    set hlsearch " may want to change this to underline
    set showmatch  " show matching bracket
" }

" Usability {
    set ruler "show where we are
    set laststatus=2 "display the status line always
    set cmdheight=2 "two lines at the bottom, to keep things from getting hidden
    set pastetoggle=<F2> "so we can paste stuff without annoying indents
" }
"
" indentation {
    set autoindent "indentation
    set shiftwidth=4
    set softtabstop=4
    set expandtab
    set backspace=indent,eol,start

    " Remap code completion to Ctrl+Space
    inoremap <Nul> <C-x><C-o>
" }
"
" nerdtree {
    let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
    noremap gn :NERDTree<Cr>
" }
"
" solarizedTheme {
    set list
    set listchars=eol:§,tab:>-,trail:~,extends:>,precedes:<
    let g:solarized_visibility='low'
    "let g:solarized_termcolors=256
    set background=dark
    colorschem solarized
" }
" Unsorted {
    set shortmess+=filmnrxoOtT      " abbrev. of messages (avoids 'hit enter')
    set viewoptions=folds,options,cursor,unix,slash " better unix / windows compatibility
    set virtualedit=onemore         " allow for cursor beyond last character
    set history=1000                " Store a ton of history (default is 20)
    set spell                       " spell checking on 
    hi clear SpellBad
    hi SpellBad cterm=underline
    set showmode "display the current mode
    set cursorline "highlights the light we're on
    hi cursorline guibg=#111111 "Sets the highlight color
    hi CursorColumn guibg=#333333 "highlights the cursor
    set whichwrap=b,s,h,l,<,>,[,] "wrap backspace and cursor

    "folding settings
    set foldmethod=indent   "fold based on indent
    set foldnestmax=10      "deepest fold is 10 levels
    set nofoldenable        "dont fold by default
    set foldlevel=1         "this is just what i use
" }
