# .bashrc file
#
# commandPrompt {
    [ -z "$PS1" ] && return # If not running interactively, don't do anything
    PS1='\u@\h:\w$(__git_ps1 "\[\e[0;90m\][%s]\[\e[0m\]")§ ' # Show git branch in status
    source ~/dotfiles/bash/git-completion.bash # Git tab completion
# }

# historySettings {
    HISTCONTROL=ignoreboth # don't put duplicate lines or lines starting with space in the history.
    shopt -s histappend # append to the history file, don't overwrite it
    HISTSIZE=1000 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
    HISTFILESIZE=2000
    shopt -s checkwinsize # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
# }

# colorSupport {
    # enable color support of ls and also add handy aliases
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        #alias dir='dir --color=auto'
        #alias vdir='vdir --color=auto'

        alias grep='grep --color=auto'
        alias fgrep='fgrep --color=auto'
        alias egrep='egrep --color=auto'
    fi
# }

# aliases {
    # some more ls aliases
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias ls='ls --color'

    # Add an "alert" alias for long running commands.  Use like so:
    #   sleep 10; alert
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

    # Alias definitions.
    # You may want to put all your additions into a separate file like
    # ~/.bash_aliases, instead of adding them here directly.
    # See /usr/share/doc/bash-doc/examples in the bash-doc package.
 
    if [ -f ~/.bash_aliases ]; then
        . ~/.bash_aliases
    fi

    # enable programmable completion features (you don't need to enable
    # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
    # sources /etc/bash.bashrc).
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        . /etc/bash_completion
    fi

    [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)" # make less more friendly for non-text input files, see lesspipe(1)

# }

# rvm {
    PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
# }
